### ISSUE TITLE
requires "curly" is missing in ferus.nimble

### ISSUE THREAD

**Issue by enthus1ast** [xTrayambak/ferus#15]
`nimble install`

fails because:

`requires "curly"`

is missing.

**Comment by xTrayambak** [comment]
Oh god. It seems somehow I forgot to add the nimble file to my commits.

**Comment by xTrayambak** [comment]
This is fixed in the cssgrid-layout branch which will be merged into experimental today, which in turn will be merged into main today. Also seems like @neroist's fork's patch-1 branch fixes this too.

**Comment by xTrayambak** [comment]
This is fixed!
