### ISSUE TITLE
undeclared routine `parseCssRules`

### ISSUE THREAD

**Issue by jtbx** [xTrayambak/ferus#22]
Since f2a148aedf0fd785c3bb062f789b0da0272c02ec there is a call to an undefined function `parseCssRules`:
https://github.com/ferus-web/ferus/blob/f2a148aedf0fd785c3bb062f789b0da0272c02ec/src/ferus.nim#L33

This is breaking the Nix build:

```
/build/jir7k5darxnndr839l1rnfwh355sjn7d-source/src/ferus.nim(33, 21) Error: attempting to call undeclared routine: 'parseCssRules'
```

Also `nimble build` emits an obscure error:
```
$ nimble build
   Building ferus/ferus using c backend
       Tip: 135 messages have been suppressed, use --verbose to show them.
nimble.nim:229           buildFromDir

    Error:  Build failed for the package: ferus
```
--verbose doesn't show anything else either.

**Comment by xTrayambak** [comment]
That's weird. I thought I'd removed it because I'm not working on the CSS rule parser for now (again) and shifting my focus to other components. I'll fix it up rq, thanks.

**Comment by xTrayambak** [comment]
Also, the reason you're getting that obscure error if you're on NixOS is because you're using a wrapped Nimble install.
Make sure that you're using `nim-unwrapped-2` and `nimble`.

**Comment by jtbx** [comment]
> Also, the reason you're getting that obscure error if you're on NixOS is because you're using a wrapped Nimble install. Make sure that you're using `nim-unwrapped-2` and `nimble`.

I'm not on NixOS but I can try to make a patch for this later
