### ISSUE TITLE
Any example

### ISSUE THREAD

**Issue by Ethosa** [xTrayambak/ferus#25]
Can you provide any working example of using ferus with OpenGL and GLFW?

I mean creating window, load HTML/CSS and show this window?

**Comment by xTrayambak** [comment]
Hey there. Ferus is still very much in its infancy right now. We had some basic HTML layout working a few months back but we scrapped it to modularize Ferus into small parts. The current branch has a simple window that opens up and shows some text, but there's a lot more going under the hood now. :)

Ferus now fully supports multiprocessing via the `ferus_ipc` library and renders things using `ferusgfx`. I hope to start working on the layout soon, and I'm open to any help for it. We even have a fully functional CSS3 parser ready for use.

I don't think we're getting close to something like Electron any time soon, but that's okay by me.

**Comment by xTrayambak** [comment]
@Ethosa We have an example now, since the new layout engine is working. You can check it out in the README.
