### ISSUE TITLE
Layout engine hackfest-ish megathread

### ISSUE THREAD

**Issue by xTrayambak** [xTrayambak/ferus#5]
Hey everyone! It's finally time for Ferus to, well, actually display HTML! This will be a megathread dedicated to slowly implementing the layout engine bit by bit. Any and all contributions are more than appreciated! Please push changes to the experimental branch, not the main branch. Once this ends, and everything is smoothed out, the experimental branch will be merged with main.

**Comment by xTrayambak** [comment]
What I'm thinking is that the layout engine will have two states -- the stack (which will be rendered by processLayout) and the layout (a TableRef[tuple[x, y: int], Box])

**Comment by xTrayambak** [comment]
The X and Y coordinates however are the literal coordinates where the box will be rendered, not what the Box's X and Y coordinates intend.

**Comment by xTrayambak** [comment]
It seems I have found an issue in the renderer itself -- it segfaults when resizing. I'm fixing it right now.

**Comment by xTrayambak** [comment]
This seems to be a pixie-related bug, not related to Ferus.

**Comment by xTrayambak** [comment]
Okay, this bug is really bizzare. Resizing works a few times, then it segfaults the 12th-14th'ish  time

**Comment by xTrayambak** [comment]
It only happens when the X coordinate exceeds 1000. Really weird stuff.

**Comment by xTrayambak** [comment]
I'll just leave this bug and focus on the layout engine for now, if anyone interested minds helping out, please do.

**Comment by xTrayambak** [comment]
Ferus can now render p1 tags. I have not commited it yet.

**Comment by xTrayambak** [comment]
Welp, I scrapped it all in favour of rewriting it to be like mbrubeck/robinson's layout engine.

**Comment by xTrayambak** [comment]
Screw it. I'm just brainstorming a layout engine on my own for now. Pray that I survive!

**Comment by xigoi** [comment]
This is an extremely ambitious project. I wish you the best of luck!

**Comment by neroist** [comment]
Me too!

**Comment by xTrayambak** [comment]
> This is an extremely ambitious project. I wish you the best of luck!

Thanks!

**Comment by xTrayambak** [comment]
> Me too!

Thank you!

**Comment by xTrayambak** [comment]
Ferus now does basic layout in the experimental branch.

**Comment by xTrayambak** [comment]
We're redoing it.... again. Yep.

**Comment by xTrayambak** [comment]
Not relevant to the project rewrite now. All discussions will be moved to [the new layout solver](https://github.com/ferus-web/vyavast)

**Comment by xTrayambak** [comment]
Layout has been moved in-tree again for the sake of my sanity. It's working a bit now.
